// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ZpZoS6XVTY8csMjOJj07nydlkO-f_ug',
    appId: '1:150508041060:web:b89ad04b0d1670f1c3c071',
    messagingSenderId: '150508041060',
    projectId: 'studentflow-516a4',
    authDomain: 'studentflow-516a4.firebaseapp.com',
    storageBucket: 'studentflow-516a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwKhpVzyOBhm6hYDWJs_PZNjNrupM0UeQ',
    appId: '1:150508041060:android:0f76dd475c27ee02c3c071',
    messagingSenderId: '150508041060',
    projectId: 'studentflow-516a4',
    storageBucket: 'studentflow-516a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmpPMaSsw_tcXe-644LEuAst9-ezajJYo',
    appId: '1:150508041060:ios:5b3b71ff8f566890c3c071',
    messagingSenderId: '150508041060',
    projectId: 'studentflow-516a4',
    storageBucket: 'studentflow-516a4.firebasestorage.app',
    iosBundleId: 'com.example.studentflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmpPMaSsw_tcXe-644LEuAst9-ezajJYo',
    appId: '1:150508041060:ios:5b3b71ff8f566890c3c071',
    messagingSenderId: '150508041060',
    projectId: 'studentflow-516a4',
    storageBucket: 'studentflow-516a4.firebasestorage.app',
    iosBundleId: 'com.example.studentflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5ZpZoS6XVTY8csMjOJj07nydlkO-f_ug',
    appId: '1:150508041060:web:17daea80cfb9687ec3c071',
    messagingSenderId: '150508041060',
    projectId: 'studentflow-516a4',
    authDomain: 'studentflow-516a4.firebaseapp.com',
    storageBucket: 'studentflow-516a4.firebasestorage.app',
  );
}
